name: Super-Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Super-Linter
        uses: github/super-linter@v4

      - name: Run Super-Linter
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
        run: |
          ./start.sh
